//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_2ISP11_17_DanArt_ArtZey.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientService()
        {
            this.ServiceDocument = new HashSet<ServiceDocument>();
        }
    
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDService { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Comment { get; set; }
        public int IDServiceStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceStatus ServiceStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceDocument> ServiceDocument { get; set; }
    }
}
