//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_2ISP11_17_DanArt_ArtZey.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public string NameGender { get; set; }
        public System.DateTime StartDate { get; set; }
        public int IDTag { get; set; }
    }
}
