//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_2ISP11_17_DanArt_ArtZey.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientDetails
    {
        public string FullName { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string NameGender { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> TagCount { get; set; }
    }
}
